### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by winston0410** [hoob3rt/lualine.nvim#299]
### Self Checks

- [X] I'm using the latest lualine and neovim nightly.
- [X] I didn't find the issue in exsisting issues or prs.

### How to reproduce the problem

Use the `tokyonight.nvim` theme, and use the following config for `lualine`

```lua
local function init(paq)
	paq({
		"hoob3rt/lualine.nvim",
		requires = { "kyazdani42/nvim-web-devicons", opt = true },
		config = function()
			-- local color
			local colors = require("tokyonight.colors").setup()
			-- print('check colors', vim.inspect(colors))
			require("lualine").setup({
				options = {
					theme = "tokyonight",
					component_separators = "",
					section_separators = "",
				},
				sections = {
					lualine_a = { "mode" },
					lualine_b = { "branch" },
					lualine_c = {},
					lualine_x = {},
					lualine_y = {
						{
							"filename",
							file_status = true,
							path = 2,
							color = { fg = colors.fg, bg = colors.bg_statusline },
						},
					},
					lualine_z = {
						{
							"diagnostics",
							sources = { "nvim_lsp" },
							symbols = { error = " ", warn = " ", info = " " },
							-- color_error = colors.red,
							-- color_warn = colors.yellow,
							-- color_info = colors.cyan,
							color = { bg = colors.bg_statusline },
						},
						{
							-- Check if active LSP exist
							function()
								local msg = ""
								local clients = vim.lsp.get_active_clients()
								if #clients < 1 then
									msg = "年"
									return msg
								end
								return ""
							end,
							color = { fg = colors.fg, bg = colors.bg_statusline },
						},
					},
				},
			})
		end,
	})
end

return {
	init = init,
}
```

### Actual behaviour

I am unable to change the highlight for diagnosis. It has the same color as mode.

<img width="1440" alt="Screenshot 2021-07-17 at 8 35 22 AM" src="https://user-images.githubusercontent.com/59228178/126029917-b69246d3-7c9b-49d0-9ad5-67b5d6cc89bf.png">

### Expected behaviour

I expect the diagnosis section uses the color that I have defined, `color = { bg = colors.bg_statusline },`

### Minimal config to reproduce the issue

<details>
<summary>Config</summary>

</details>

**Comment by shadmansaleh** [comment]
This is a bug with `diff` & `diagnostics` component .
As these are the only ones that create internal highlight groups with `create_component_highlight_group`.

https://github.com/hoob3rt/lualine.nvim/blob/9726824f1dcc8907632bc7c32f9882f26340f815/lua/lualine/highlight.lua#L73-L118

The main issue is `create_component_highlight_group` doesn't account for user's color changes .

**Comment by winston0410** [comment]
So how can I override the highlight setting, or is it impossible right now?

I have tried this, but it complains that `effect` is not a correct value for `gui`

```lua
						{
							"diagnostics",
							sources = { "nvim_lsp" },
							symbols = { error = " ", warn = " ", info = " " },
							-- color_error = colors.red,
							-- color_warn = colors.yellow,
							-- color_info = colors.cyan,
							color = { bg = colors.bg_statusline, gui = "effect" },
						},
```

**Comment by shadmansaleh** [comment]
> So how can I override the highlight setting, or is it impossible right now?

Until that bug is fixed. Your overwrites wont work for diff & diagnostic . The fix is quite simple . But @hoob3rt needs to find some time to merge it :P  . 

Also where did you get 'effect' valid gui values are the ones that are listed in `:h attr-list`

**Comment by shadmansaleh** [comment]
Fixed in #311

**Comment by winston0410** [comment]
Just switch to your branch and tested again, yet I am still getting the same error as before, where I cannot control the highlight group.

**Comment by shadmansaleh** [comment]
> @shadmansaleh Just switch to your branch and tested again, yet I am still getting the same error as before

Strange . Are you sure you were on my branch ? I don't get the error with your config any more :/

**Comment by winston0410** [comment]
@shadmansaleh You were right, I have updated the branch in config, yet I haven't delete the existing plugin. After I have done that it works now! Thank you so much
