### ISSUE TITLE
Add a tabline component

### ISSUE THREAD

**Issue by Hubro** [hoob3rt/lualine.nvim#332]
### Requested feature

When configuring the tabline in lualine, it completely overrides the built-in tab line, meaning I can no longer see which tabs are open or which tab I'm on.

Why can't we have both, though? :slightly_smiling_face: It's super neat to have the filename at the top left, for example:

![image](https://user-images.githubusercontent.com/597206/132208407-3e184ea1-9b02-40b0-b954-bb779dca7dec.png)

But there's still lots of space available at the top right. It would be nice to have a very simple component that displays a list of tabs and highlights the active tab, so we can make use of the space at the top of the file and still retain the functionality of the original tabline.

### Motivation

My guess is that a fair number of people refrain from configuring the tabline with lualine because that means losing the original functionality of the tabline completely. A small component that restores that original functionality would open up a lot of options for those people (including me :innocent:).

As a bonus, it sounds (at least in theory) super easy to implement. The component would just need to list the tabs with a separator between them, then highlight the active one in some way.

**Comment by shadmansaleh** [comment]
Try out [tabline.nvim](https://github.com/kdheepak/tabline.nvim)

**Comment by Hubro** [comment]
@shadmansaleh Doesn't seem to work with your fork. I opened an issue: https://github.com/kdheepak/tabline.nvim/issues/16

**Comment by kdheepak** [comment]
I've fixed the issue now. It should work with both hoob3rt and shadmansaleh version of lualine now.

**Comment by snorkysnark** [comment]
Except it's a bufferline, and I just want vanilla tabs.
[luatab.nvim](https://github.com/alvarosevilla95/luatab.nvim) works, but it breaks lualine's separators (custom component on the right should start with a triangle)

![lualine](https://user-images.githubusercontent.com/36006338/132868336-b4223eb4-7396-4e62-846e-62d7ceb41553.png)

Also, I'd 'appreciate something that synced with lualine's theme, had separators (maybe devicons), but functioned like a simple tabline

**Comment by kdheepak** [comment]
Showing only tabs is possible with `tabline.nvim`, although at the moment the color and separators work as you’d expect correctly for `section_z`. I’ll plan on updating it so that it works in any section. 

@shadmansaleh, this appears to be a popular request. What are your thoughts about adding this functionality to `lualine.nvim`? I can submit a PR for this if you think that’s a good idea.

**Comment by shadmansaleh** [comment]
It indeed seems like a quite popular request . It's been requested many times . If you look at issue tracker I was [first](https://github.com/hoob3rt/lualine.nvim/issues/89#issue-803162100) to ask for it . @hoob3rt was quite uninterested idea that's why we didn't get a bufferline/tabline component .

I think I'm in favor of adding it to lualine.Though it'll have to be much striped down version of tabline.nvim . I think we can get rid of most of the rendering code anyway and let lualine handle the rendering that'll fix the visual issues too I think .

I'll really busy right now else I'd have done it myself . You can through in a pr and we'll take a look . Also can ask me if you need any help/info :)

**Comment by kdheepak** [comment]
I expect it’ll have to be a stripped down version too. I’ll make a draft PR and we can continue the discussion there! Thanks!

**Comment by Hubro** [comment]
@shadmansaleh @kdheepak A little off topic, but I just updated all my plugins and tabline stopped working in lualine. My config:

```lua
tabline = {
  lualine_a = {
    "filename",
  },
  lualine_b = {
    { gps.get_location, cond = gps.is_available }
  },
  lualine_x = { tabline.tabline_tabs },
}
```

![image](https://user-images.githubusercontent.com/597206/133403060-c4807bff-b80d-4025-b057-9d51f506a1d1.png)

**Comment by shadmansaleh** [comment]
@kdheepak You'll need to adopt the newer separator.left and right scheme . That's why tabline is failing. separator as list was deprecated in 2f801ed6221abfb00f74e34c35ccd4d1153c2b07

tabline seems to work with this patch

```diff
diff --git a/lua/tabline.lua b/lua/tabline.lua
index c1f30ae..0c643e4 100644
--- a/lua/tabline.lua
+++ b/lua/tabline.lua
@@ -753,20 +753,20 @@ function M.setup(opts)
     else
       error("Unable to load separators from lualine")
     end
-    M.options.component_left = cs[1]
-    M.options.component_right = cs[2]
-    M.options.section_left = ss[1]
-    M.options.section_right = ss[2]
+    M.options.component_left = cs.left
+    M.options.component_right = cs.right
+    M.options.section_left = ss.left
+    M.options.section_right = ss.right
   end
 
   if opts.options.component_separators ~= nil then
-    M.options.component_left = opts.options.component_separators[1]
-    M.options.component_right = opts.options.component_separators[2]
+    M.options.component_left = opts.options.component_separators.left
+    M.options.component_right = opts.options.component_separators.right
   end
 
   if opts.options.section_separators ~= nil then
-    M.options.section_left = opts.options.section_separators[1]
-    M.options.section_right = opts.options.section_separators[2]
+    M.options.section_left = opts.options.section_separators.left
+    M.options.section_right = opts.options.section_separators.right
   end
 
   if opts.options.max_bufferline_percent then
```

**Comment by kdheepak** [comment]
Thanks for looking into this and sharing the patch! I’ll update the plugin.

**Comment by kdheepak** [comment]
Fixed in most recent commit of `tabline.nvim`.

**Comment by shadmansaleh** [comment]
@kdheepak by the way setting `tabline_show_filename_only` to true doesn't seem to do anything it still shows relative file path.

**Comment by kdheepak** [comment]
It seems to work for me?

<img width="1680" alt="Screen Shot 2021-09-15 at 4 44 28 AM" src="https://user-images.githubusercontent.com/1813121/133419717-ea00945c-a634-4854-b2f9-fb9c3e93666f.png">

This is the logic for finding the name of the buffer:

https://github.com/kdheepak/tabline.nvim/blob/f3038875c2827f2c880a760cf27802fd949e3d1f/lua/tabline.lua#L304-L331

**Comment by shadmansaleh** [comment]
This is the right way to do it right ?
```lua
tabline.setup {
  enable = false,
  options = {
    tabline_show_filename_only = true,
  },
}
```

**Comment by kdheepak** [comment]
Ugh, you are right, my bad. I'll make it work both ways.

**Comment by kdheepak** [comment]
Fixed in https://github.com/kdheepak/tabline.nvim/commit/280911a835fadc6f4fe82e736c300100e2d60dd6.

**Comment by shadmansaleh** [comment]
Thanks for the quick fix.

**Comment by shadmansaleh** [comment]
https://github.com/shadmansaleh/lualine.nvim/pull/42 has been merged now lualine has tradirional tabline / bufferline support.
